version: "3"
services:
    db: 
        image: postgres
        env_file: 
            - ./BDD/database.env
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./BDD/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        networks:
            - reseau
    backend:
        image: back
        depends_on:
            - db
        ports:
            - "3000:3000"
        networks:
            - reseau
        environment:
            DB_USER: eric
            DB_PASSWORD: toto123
            DB_HOST: db
            DB_PORT: 5432
            DB_NAME: todolist_db
    frontend:
        image: front
        depends_on: 
            - backend
        ports:
            - "80:80"
        networks: 
            - reseau
networks: 
    reseau:
volumes:
    pgdata: