version: "3"
services:
    todolist:
        image: front
        depends_on: 
            - backend
        ports:
            - "80:80"
        networks: 
            - reseau
    backend:
        image: back
        ports:
            - "3000:3000"
        networks: 
            - reseau
networks: 
    reseau:
