version: "3"
services:
    db: 
        image: postgres
        env_file: 
            - ./BDD/database.env
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./BDD/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
    backend:
        image: back
        depends_on:
            - db
        ports:
            - "3000:3000"
        networks:
            - reseau
    frontend:
        image: front
        depends_on: 
            - backend
        ports:
            - "80:80"
        networks: 
            - reseau
networks: 
    reseau:
volumes:
    pgdata: